/**
 * GENERATED by src/spikes/_gen_google_catalog.ts from Google's Discovery service.
 * Do not hand-edit: re-run the generator instead.
 *
 * Every field here is published by Google. What is NOT here -- the service account, the
 * `Bearer {access_token}` header, the domain-wide-delegation subject -- is identical for
 * every Workspace app and lives once in googleConnectors() rather than being retyped per
 * app. Hand-typing it per app is what left shared_googlecalendar, shared_googlecontacts and
 * shared_googlechat with no impersonation block, which silently broke every INVOKER agent on
 * those three connectors.
 *
 * `scope` is the DWD grant the admin authorizes, deliberately the app's broad scope: DWD
 * matches scope strings exactly, so the grant must cover the widest string any migration
 * will request. Narrowing what each agent REQUESTS happens per migration, not here.
 *
 * Adding a Google app: add it to APPS in the generator and re-run. No new file, no new
 * registry entry, no new Python module.
 */
export interface GoogleAppRow {
  /** Google Discovery api name — the key for looking its methods up at build time. */
  api: string;
  id: string;
  name: string;
  category: string;
  icon: string;
  docsUrl: string;
  baseUrlTemplate: string;
  /** The exact string the Workspace admin authorizes for domain-wide delegation. */
  scope: string;
}

export const GOOGLE_APPS: GoogleAppRow[] = [
  {
    api: 'gmail',
    id: 'shared_gmail',
    name: "Gmail",
    category: 'storage',
    icon: '✉️',
    docsUrl: 'https://developers.google.com/workspace/gmail/api/',
    baseUrlTemplate: 'https://gmail.googleapis.com/gmail/v1',
    scope: 'https://www.googleapis.com/auth/gmail.modify',
  },
  {
    api: 'drive',
    id: 'shared_googledrive',
    name: "Google Drive",
    category: 'storage',
    icon: '📁',
    docsUrl: 'https://developers.google.com/workspace/drive/',
    baseUrlTemplate: 'https://www.googleapis.com/drive/v3',
    scope: 'https://www.googleapis.com/auth/drive',
  },
  {
    api: 'calendar',
    id: 'shared_googlecalendar',
    name: "Calendar",
    category: 'storage',
    icon: '📅',
    docsUrl: 'https://developers.google.com/workspace/calendar/firstapp',
    baseUrlTemplate: 'https://www.googleapis.com/calendar/v3',
    scope: 'https://www.googleapis.com/auth/calendar',
  },
  {
    api: 'people',
    id: 'shared_googlecontacts',
    name: "People",
    category: 'storage',
    icon: '📇',
    docsUrl: 'https://developers.google.com/people/',
    baseUrlTemplate: 'https://people.googleapis.com/v1',
    scope: 'https://www.googleapis.com/auth/contacts',
  },
  {
    api: 'chat',
    id: 'shared_googlechat',
    name: "Google Chat",
    category: 'messaging',
    icon: '💬',
    docsUrl: 'https://developers.google.com/workspace/chat',
    baseUrlTemplate: 'https://chat.googleapis.com/v1',
    scope: 'https://www.googleapis.com/auth/chat.messages https://www.googleapis.com/auth/chat.spaces',
  },
  {
    api: 'sheets',
    id: 'shared_googlesheet',
    name: "Google Sheets",
    category: 'storage',
    icon: '📊',
    docsUrl: 'https://developers.google.com/workspace/sheets/',
    baseUrlTemplate: 'https://sheets.googleapis.com/v4',
    scope: 'https://www.googleapis.com/auth/spreadsheets',
  },
  {
    api: 'docs',
    id: 'shared_googledocs',
    name: "Google Docs",
    category: 'storage',
    icon: '📄',
    docsUrl: 'https://developers.google.com/workspace/docs/',
    baseUrlTemplate: 'https://docs.googleapis.com/v1',
    scope: 'https://www.googleapis.com/auth/documents',
  },
  {
    api: 'slides',
    id: 'shared_googleslides',
    name: "Google Slides",
    category: 'storage',
    icon: '📑',
    docsUrl: 'https://developers.google.com/workspace/slides/',
    baseUrlTemplate: 'https://slides.googleapis.com/v1',
    scope: 'https://www.googleapis.com/auth/presentations',
  },
  {
    api: 'tasks',
    id: 'shared_googletasks',
    name: "Google Tasks",
    category: 'collaboration',
    icon: '✅',
    docsUrl: 'https://developers.google.com/workspace/tasks/',
    baseUrlTemplate: 'https://tasks.googleapis.com/tasks/v1',
    scope: 'https://www.googleapis.com/auth/tasks',
  },
  {
    api: 'forms',
    id: 'shared_googleforms',
    name: "Google Forms",
    category: 'collaboration',
    icon: '📝',
    docsUrl: 'https://developers.google.com/workspace/forms/api',
    baseUrlTemplate: 'https://forms.googleapis.com/v1',
    scope: 'https://www.googleapis.com/auth/forms.body',
  },
];
