/**
 * Auto-discover EVERY real flow-backed tool on the source Deal Desk agent (live from
 * Dataverse, not a hardcoded list), and attempt the same live translate-and-upload
 * pipeline for each one. Reports honestly per-flow: fully translated (Compose-only
 * shape, verified ground truth), or unmapped (uses a connector/filter action this
 * codebase hasn't ground-truth-verified the Application Integration shape for yet) --
 * never guesses at an unverified shape.
 *
 * Usage: npx tsx src/spikes/_diag_auto_migrate_all_flows.ts [--upload]
 * Without --upload, generates and prints the JSON for each flow but does not call
 * the real upload API (safe dry run). With --upload, actually uploads each
 * successfully-translated flow as "<Name>_AutoGenerated".
 */
import 'dotenv/config';
import { connectMongo } from '../db/mongo.js';
import { getDb } from '../db/core.js';
import { clientCredsToken } from '../auth/microsoft.js';
import { getSaToken } from '../auth/google.js';
import type { Session } from '../sessionStore.js';

const DO_UPLOAD = process.argv.includes('--upload');
const GCP_PROJECT = 'agentmigrations';
const GCP_LOCATION = 'us-east1';

await connectMongo();
const s = (await getDb()
  .collection('migrationSessions')
  .find({ tenantId: { $exists: true }, dvOrgUrl: { $exists: true } })
  .sort({ $natural: -1 })
  .limit(1)
  .next()) as Session | null;
if (!s || !s.tenantId || !s.dvOrgUrl) throw new Error('NO_USABLE_DATAVERSE_SESSION');

const dvBase = s.dvOrgUrl.replace(/\/$/, '');
const dvToken = await clientCredsToken(s.tenantId, s.dvOrgUrl);
const dvHeaders = { Authorization: `Bearer ${dvToken}`, Accept: 'application/json' };

// ── 1. Auto-discover every flow-backed tool on Deal Desk (live) ──

const botRes = await fetch(`${dvBase}/api/data/v9.2/bots?$filter=${encodeURIComponent("name eq 'Deal Desk'")}&$select=botid`, { headers: dvHeaders });
const botId = ((await botRes.json()) as { value?: Array<{ botid: string }> }).value?.[0]?.botid;
if (!botId) throw new Error('BOT_NOT_FOUND');

const compRes = await fetch(
  `${dvBase}/api/data/v9.2/botcomponents?$select=name,data,content&$filter=${encodeURIComponent(`_parentbotid_value eq ${botId}`)}&$top=500`,
  { headers: dvHeaders },
);
const comps = ((await compRes.json()) as { value?: Array<{ name: string; data?: string; content?: string }> }).value ?? [];
const flowTools: Array<{ name: string; flowId: string }> = [];
for (const c of comps) {
  const blob = c.data || c.content || '';
  if (!/invokeflowtaskaction/i.test(blob)) continue;
  const m = /^\s*flowId:\s*(\S+)\s*$/im.exec(blob);
  if (m) flowTools.push({ name: c.name, flowId: m[1] });
}
console.log(`Discovered ${flowTools.length} real flow-backed tool(s) on Deal Desk (live): ${flowTools.map((t) => t.name).join(', ')}\n`);

// ── 2. Translation helpers (VERIFIED Compose/FieldMappingTask shape only) ──

type Segment = { type: 'literal'; value: string } | { type: 'ref'; field: string };

function splitTemplate(template: string, fieldNameByKey: Record<string, string>): Segment[] {
  const segments: Segment[] = [];
  const re = /@\{triggerBody\(\)\?\['(\w+)'\]\}/g;
  let lastIndex = 0;
  let m: RegExpExecArray | null;
  while ((m = re.exec(template))) {
    if (m.index > lastIndex) segments.push({ type: 'literal', value: template.slice(lastIndex, m.index) });
    segments.push({ type: 'ref', field: fieldNameByKey[m[1]] ?? m[1] });
    lastIndex = re.lastIndex;
  }
  if (lastIndex < template.length) segments.push({ type: 'literal', value: template.slice(lastIndex) });
  return segments;
}
function valueOf(seg: Segment) {
  return seg.type === 'literal' ? { literalValue: { stringValue: seg.value } } : { referenceValue: `$${seg.field}$` };
}
function buildChain(segments: Segment[], i: number): any {
  const node: any = { initialValue: valueOf(segments[i]) };
  if (i < segments.length - 1) {
    node.transformationFunctions = [{ functionType: { stringFunction: { functionName: 'CONCAT' } }, parameters: [buildChain(segments, i + 1)] }];
  }
  return node;
}

// ── 3. Process each discovered flow ──

const summary: Array<{ name: string; result: string }> = [];

for (const tool of flowTools) {
  console.log(`${'='.repeat(60)}\nFLOW: ${tool.name}`);
  try {
    const wfRes = await fetch(`${dvBase}/api/data/v9.2/workflows(${tool.flowId})?$select=name,clientdata`, { headers: dvHeaders });
    const wf = (await wfRes.json()) as { name: string; clientdata?: string };
    if (!wf.clientdata) throw new Error('no clientdata');
    const parsed = JSON.parse(wf.clientdata);
    const def = parsed.properties?.definition ?? parsed.definition;

    const trigger = def.triggers?.manual;
    const inputProps: Record<string, { title?: string; description?: string }> = trigger?.inputs?.schema?.properties ?? {};
    const fieldNameByKey: Record<string, string> = {};
    for (const [key, meta] of Object.entries(inputProps)) fieldNameByKey[key] = (meta.description || meta.title || key).trim();
    const inputFieldNames = Object.values(fieldNameByKey);

    const actions: Record<string, any> = def.actions ?? {};
    const composeActions = Object.entries(actions).filter(([, a]) => a.type === 'Compose');
    const connectorActions = Object.entries(actions).filter(([, a]) => a.type === 'OpenApiConnection');
    const queryActions = Object.entries(actions).filter(([, a]) => a.type === 'Query');
    const responseAction = Object.entries(actions).find(([, a]) => a.type === 'Response');

    console.log(`  Inputs: ${inputFieldNames.join(', ')}`);
    if (connectorActions.length) console.log(`  ⚠ UNMAPPED: ${connectorActions.length} connector action(s) (${connectorActions.map(([n]) => n).join(', ')}) — no ground-truth Application Integration shape yet, not guessed`);
    if (queryActions.length) console.log(`  ⚠ UNMAPPED: ${queryActions.length} filter/query action(s) (${queryActions.map(([n]) => n).join(', ')}) — needs a JavaScript-task equivalent, not yet built`);

    if (!composeActions.length) {
      console.log(`  RESULT: cannot auto-translate yet — this flow has no Compose action for the verified FieldMappingTask path (uses connector/filter actions instead).`);
      summary.push({ name: tool.name, result: 'UNMAPPED (connector/filter-based, no ground truth yet)' });
      continue;
    }

    const [, composeAction] = composeActions[0];
    const segments = splitTemplate(composeAction.inputs, fieldNameByKey);
    const outputVarTitle = responseAction ? Object.values<any>(responseAction[1].inputs?.schema?.properties ?? {})[0]?.title ?? 'Output' : 'Output';

    const fieldMappingConfig = {
      '@type': 'type.googleapis.com/enterprise.crm.eventbus.proto.FieldMappingConfig',
      mappedFields: [
        {
          inputField: { fieldType: 'STRING_VALUE', transformExpression: buildChain(segments, 0) },
          outputField: { referenceKey: `$${outputVarTitle}$`, fieldType: 'STRING_VALUE', cardinality: 'OPTIONAL' },
        },
      ],
    };
    const newName = `${tool.name.replace(/\s+/g, '')}_AutoGenerated`;
    const integrationDefinition = {
      description: `Auto-migrated from Copilot Studio flow "${wf.name}".`,
      triggerConfigs: [
        {
          label: 'API Trigger',
          startTasks: [{ taskId: '1' }],
          properties: { 'Trigger name': `${newName}_API_1` },
          triggerType: 'API',
          triggerNumber: '1',
          triggerId: `api_trigger/${newName}_API_1`,
          inputVariables: { names: inputFieldNames },
          outputVariables: {},
        },
      ],
      taskConfigs: [
        {
          task: 'FieldMappingTask',
          taskId: '1',
          parameters: { FieldMappingConfigTaskParameterKey: { key: 'FieldMappingConfigTaskParameterKey', value: { jsonValue: JSON.stringify(fieldMappingConfig) } } },
          taskExecutionStrategy: 'WHEN_ALL_SUCCEED',
          displayName: 'Data Mapping',
          externalTaskType: 'NORMAL_TASK',
        },
      ],
      integrationParameters: [
        ...inputFieldNames.map((name) => ({ key: name, dataType: 'STRING_VALUE', defaultValue: { stringValue: '' }, displayName: name, inputOutputType: 'IN' })),
        { key: outputVarTitle, dataType: 'STRING_VALUE', defaultValue: { stringValue: '' }, displayName: outputVarTitle, inputOutputType: 'OUT' },
      ],
    };

    console.log(`  Translated successfully (${segments.length} template segments -> CONCAT chain).`);
    if (DO_UPLOAD) {
      const gToken = await getSaToken();
      const uploadUrl = `https://${GCP_LOCATION}-integrations.googleapis.com/v1/projects/${GCP_PROJECT}/locations/${GCP_LOCATION}/integrations/${newName}/versions:upload`;
      const uploadRes = await fetch(uploadUrl, {
        method: 'POST',
        headers: { Authorization: `Bearer ${gToken}`, 'Content-Type': 'application/json' },
        body: JSON.stringify({ content: JSON.stringify(integrationDefinition), fileFormat: 'JSON' }),
      });
      console.log(`  Upload status: ${uploadRes.status}`);
      if (!uploadRes.ok) console.log(`  ${(await uploadRes.text()).slice(0, 300)}`);
      summary.push({ name: tool.name, result: uploadRes.ok ? `UPLOADED as ${newName}` : `translated but upload failed (${uploadRes.status})` });
    } else {
      console.log('  (dry run — pass --upload to actually create it)');
      summary.push({ name: tool.name, result: 'translated OK (dry run, not uploaded)' });
    }
  } catch (e) {
    console.log(`  ERROR: ${(e as Error).message}`);
    summary.push({ name: tool.name, result: `error: ${(e as Error).message}` });
  }
}

console.log(`\n${'='.repeat(60)}\nSUMMARY`);
for (const row of summary) console.log(`  ${row.name}: ${row.result}`);
process.exit(0);
