/**
 * Real translator: fetch ONE named Copilot Studio flow's actual live clientdata from
 * Dataverse, parse it, generate the equivalent Application Integration
 * triggerConfigs/taskConfigs/integrationParameters JSON, and upload it as a NEW
 * integration via the real Application Integration API. No hardcoded copy of the
 * source flow's content -- everything is read live and translated by code.
 *
 * VERIFIED ground truth (from downloading our own hand-built DraftFollowUpEmail
 * integration): API trigger shape, FieldMappingTask/CONCAT-chain shape for
 * Compose-style string-templating actions. Applied here for real.
 *
 * NOT YET ground-truth-verified: connector-backed actions (OpenApiConnection in the
 * source). Per this project's lossless/honest principle, those are NOT guessed at --
 * they are reported as unmapped rather than emitting a taskConfig shape we haven't
 * confirmed against a real example.
 *
 * Usage: npx tsx src/spikes/_diag_auto_migrate_flow.ts <SourceFlowToolName> <NewIntegrationName>
 * Example: npx tsx src/spikes/_diag_auto_migrate_flow.ts DraftFollowUpEmail DraftFollowUpEmail_AutoGenerated
 */
import 'dotenv/config';
import { connectMongo } from '../db/mongo.js';
import { getDb } from '../db/core.js';
import { clientCredsToken } from '../auth/microsoft.js';
import { getSaToken } from '../auth/google.js';
import type { Session } from '../sessionStore.js';

const SOURCE_TOOL_NAME = process.argv[2] ?? 'DraftFollowUpEmail';
const NEW_INTEGRATION_NAME = process.argv[3] ?? `${SOURCE_TOOL_NAME}_AutoGenerated`;
const GCP_PROJECT = 'agentmigrations';
const GCP_LOCATION = 'us-east1';

// ── 1. Fetch the real source flow definition from Dataverse (live, not hardcoded) ──

await connectMongo();
const s = (await getDb()
  .collection('migrationSessions')
  .find({ tenantId: { $exists: true }, dvOrgUrl: { $exists: true } })
  .sort({ $natural: -1 })
  .limit(1)
  .next()) as Session | null;
if (!s || !s.tenantId || !s.dvOrgUrl) throw new Error('NO_USABLE_DATAVERSE_SESSION');

const dvBase = s.dvOrgUrl.replace(/\/$/, '');
const dvToken = await clientCredsToken(s.tenantId, s.dvOrgUrl);
const dvHeaders = { Authorization: `Bearer ${dvToken}`, Accept: 'application/json' };

const botRes = await fetch(`${dvBase}/api/data/v9.2/bots?$filter=${encodeURIComponent("name eq 'Deal Desk'")}&$select=botid`, { headers: dvHeaders });
const botJson = (await botRes.json()) as { value?: Array<{ botid: string }> };
const botId = botJson.value?.[0]?.botid;
if (!botId) throw new Error('BOT_NOT_FOUND');

const compRes = await fetch(
  `${dvBase}/api/data/v9.2/botcomponents?$select=name,data,content&$filter=${encodeURIComponent(`_parentbotid_value eq ${botId}`)}&$top=500`,
  { headers: dvHeaders },
);
const compJson = (await compRes.json()) as { value?: Array<{ name: string; data?: string; content?: string }> };
const toolComp = (compJson.value ?? []).find(
  (c) => c.name === SOURCE_TOOL_NAME || (c.data || c.content || '').includes(`modelDisplayName: ${SOURCE_TOOL_NAME}`),
);
if (!toolComp) throw new Error(`SOURCE_TOOL_NOT_FOUND: ${SOURCE_TOOL_NAME}`);
const blob = toolComp.data || toolComp.content || '';
const flowIdMatch = /^\s*flowId:\s*(\S+)\s*$/im.exec(blob);
if (!flowIdMatch) throw new Error('NO_FLOWID_ON_TOOL_COMPONENT');
const flowId = flowIdMatch[1];

const wfRes = await fetch(`${dvBase}/api/data/v9.2/workflows(${flowId})?$select=name,clientdata`, { headers: dvHeaders });
const wf = (await wfRes.json()) as { name: string; clientdata?: string };
if (!wf.clientdata) throw new Error('NO_CLIENTDATA');
const parsed = JSON.parse(wf.clientdata);
const def = parsed.properties?.definition ?? parsed.definition;
console.log(`Fetched real source flow "${wf.name}" (${flowId}) live from Dataverse.`);

// ── 2. Parse the source trigger + actions ──

const trigger = def.triggers?.manual;
if (!trigger) throw new Error('NO_MANUAL_TRIGGER');
const inputProps: Record<string, { title?: string; description?: string; type?: string }> = trigger.inputs?.schema?.properties ?? {};
const fieldNameByKey: Record<string, string> = {};
for (const [key, meta] of Object.entries(inputProps)) {
  fieldNameByKey[key] = (meta.description || meta.title || key).trim();
}
const inputFieldNames = Object.values(fieldNameByKey);
console.log(`Trigger inputs (source key -> destination name): ${JSON.stringify(fieldNameByKey)}`);

const actions: Record<string, any> = def.actions ?? {};
const composeActions = Object.entries(actions).filter(([, a]) => a.type === 'Compose');
const connectorActions = Object.entries(actions).filter(([, a]) => a.type === 'OpenApiConnection');
const responseAction = Object.entries(actions).find(([, a]) => a.type === 'Response');

if (connectorActions.length) {
  console.log(
    `\n⚠ UNMAPPED (honest, not guessed): ${connectorActions.length} connector action(s) found ` +
      `(${connectorActions.map(([n]) => n).join(', ')}). Connector taskConfig shape is not yet ` +
      `ground-truth verified in this codebase -- these are reported, not translated.`,
  );
}

// ── 3. Build the FieldMappingConfig for each Compose action (VERIFIED shape) ──

type Segment = { type: 'literal'; value: string } | { type: 'ref'; field: string };

function splitTemplate(template: string): Segment[] {
  const segments: Segment[] = [];
  const re = /@\{triggerBody\(\)\?\['(\w+)'\]\}/g;
  let lastIndex = 0;
  let m: RegExpExecArray | null;
  while ((m = re.exec(template))) {
    if (m.index > lastIndex) segments.push({ type: 'literal', value: template.slice(lastIndex, m.index) });
    const sourceKey = m[1];
    segments.push({ type: 'ref', field: fieldNameByKey[sourceKey] ?? sourceKey });
    lastIndex = re.lastIndex;
  }
  if (lastIndex < template.length) segments.push({ type: 'literal', value: template.slice(lastIndex) });
  return segments;
}

function valueOf(seg: Segment) {
  return seg.type === 'literal' ? { literalValue: { stringValue: seg.value } } : { referenceValue: `$${seg.field}$` };
}

function buildChain(segments: Segment[], i: number): any {
  const node: any = { initialValue: valueOf(segments[i]) };
  if (i < segments.length - 1) {
    node.transformationFunctions = [
      {
        functionType: { stringFunction: { functionName: 'CONCAT' } },
        parameters: [buildChain(segments, i + 1)],
      },
    ];
  }
  return node;
}

if (!composeActions.length) throw new Error('NO_COMPOSE_ACTION_FOUND — this flow needs a different translation path (not yet built)');
const [, composeAction] = composeActions[0];
const template: string = composeAction.inputs;
const segments = splitTemplate(template);
console.log(`\nCompose template split into ${segments.length} segments (literal + reference), building CONCAT chain...`);

const outputVarTitle = responseAction
  ? Object.values<any>(responseAction[1].inputs?.schema?.properties ?? {})[0]?.title ?? 'Output'
  : 'Output';

const fieldMappingConfig = {
  '@type': 'type.googleapis.com/enterprise.crm.eventbus.proto.FieldMappingConfig',
  mappedFields: [
    {
      inputField: { fieldType: 'STRING_VALUE', transformExpression: buildChain(segments, 0) },
      outputField: { referenceKey: `$${outputVarTitle}$`, fieldType: 'STRING_VALUE', cardinality: 'OPTIONAL' },
    },
  ],
};

// ── 4. Assemble the full integration definition (VERIFIED top-level shape) ──

const integrationDefinition = {
  description: def.description || `Auto-migrated from Copilot Studio flow "${wf.name}".`,
  triggerConfigs: [
    {
      label: 'API Trigger',
      startTasks: [{ taskId: '1' }],
      properties: { 'Trigger name': `${NEW_INTEGRATION_NAME}_API_1` },
      triggerType: 'API',
      triggerNumber: '1',
      triggerId: `api_trigger/${NEW_INTEGRATION_NAME}_API_1`,
      inputVariables: { names: inputFieldNames },
      outputVariables: {},
    },
  ],
  taskConfigs: [
    {
      task: 'FieldMappingTask',
      taskId: '1',
      parameters: {
        FieldMappingConfigTaskParameterKey: {
          key: 'FieldMappingConfigTaskParameterKey',
          value: { jsonValue: JSON.stringify(fieldMappingConfig) },
        },
      },
      taskExecutionStrategy: 'WHEN_ALL_SUCCEED',
      displayName: 'Data Mapping',
      externalTaskType: 'NORMAL_TASK',
    },
  ],
  integrationParameters: [
    ...inputFieldNames.map((name) => ({
      key: name,
      dataType: 'STRING_VALUE',
      defaultValue: { stringValue: '' },
      displayName: name,
      inputOutputType: 'IN',
    })),
    {
      key: outputVarTitle,
      dataType: 'STRING_VALUE',
      defaultValue: { stringValue: '' },
      displayName: outputVarTitle,
      inputOutputType: 'OUT',
    },
  ],
};

console.log('\n---- Generated Application Integration definition ----');
console.log(JSON.stringify(integrationDefinition, null, 2));

// ── 5. Upload as a NEW integration via the real API ──

const gToken = await getSaToken();
const uploadUrl = `https://${GCP_LOCATION}-integrations.googleapis.com/v1/projects/${GCP_PROJECT}/locations/${GCP_LOCATION}/integrations/${NEW_INTEGRATION_NAME}/versions:upload`;
const uploadRes = await fetch(uploadUrl, {
  method: 'POST',
  headers: { Authorization: `Bearer ${gToken}`, 'Content-Type': 'application/json' },
  body: JSON.stringify({ content: JSON.stringify(integrationDefinition), fileFormat: 'JSON' }),
});
console.log(`\nUpload status: ${uploadRes.status}`);
console.log(await uploadRes.text());
process.exit(0);
