/**
 * Populates the clean registry (connectors + connectorOperations) with the FULL list of
 * "Publisher: Microsoft" connectors the user supplied — every one Microsoft has published
 * a wrapper for, whether the underlying SERVICE is Microsoft's own or a third party's.
 *
 * Each entry is tagged with isMicrosoftOwnService based on who actually owns the real
 * service behind it (Teams/SharePoint = true; Salesforce/Dropbox/Zendesk = false) — NOT
 * assumed true just because the connector's publisher field says Microsoft.
 *
 * Two exact duplicates from the source list are deliberately excluded:
 *   shared_commondataservice      -> same product as shared_commondataserviceforapps
 *   shared_servicebus-1           -> same product as shared_servicebus
 *
 * Run: npx tsx src/spikes/_prep_populate_full_connector_registry.ts
 */
import { connectDb, closeDb } from '../db/core.js';
import { captureOpIndex } from '../connectors/captureOpIndex.js';
import { putConnector, putConnectorOperations, toRegistryRecords } from '../db/repos/connectorRegistry.js';
import { config } from '../config.js';

const CTX = {
  tenantId: '807d6772-847c-40e2-9bec-e2c930b3a42e',
  environmentId: '7f9f87cc-464e-e470-95bb-363b7f227200',
  scope: '6a5dfdff7cf05623332758b7',
};

// [connectorId, category, isMicrosoftOwnService]
const CONNECTORS: Array<[string, string, boolean]> = [
  ['shared_sharepointonline', 'content', true],
  ['shared_onedriveforbusiness', 'content', true],
  ['shared_dynamicscrmonline', 'business-apps', true],
  ['shared_salesforce', 'crm', false],
  ['shared_sql', 'data', false],
  ['shared_dropbox', 'content', false],
  ['shared_a365adminmcp', 'ai', true],
  ['shared_a365copilotchatmcp', 'ai', true],
  ['shared_a365memcp', 'ai', true],
  ['shared_a365outlookcalendarmcp', 'ai', true],
  ['shared_a365outlookmailmcp', 'ai', true],
  ['shared_a365teamsmcp', 'ai', true],
  ['shared_a365wordmcp', 'ai', true],
  ['shared_aci', 'azure', true],
  ['shared_acl', 'azure', true],
  ['shared_acschat', 'azure', true],
  ['shared_acsemail', 'azure', true],
  ['shared_acsidentity', 'azure', true],
  ['shared_acssmsevents', 'azure', true],
  ['shared_adobecommerce', 'commerce', false],
  ['shared_adomcpserver', 'devops', true],
  ['shared_agentsdk', 'ai', true],
  ['shared_alchemy', 'productivity', true],
  ['shared_amazonredshift', 'data', false],
  ['shared_amazons3', 'content', false],
  ['shared_amazonsqs', 'messaging', false],
  ['shared_appfigures', 'analytics', false],
  ['shared_applicationinsights', 'azure', true],
  ['shared_approvals', 'productivity', true],
  ['shared_arm', 'azure', true],
  ['shared_asana', 'productivity', false],
  ['shared_asdr', 'other', false],
  ['shared_assistantstudiov2', 'business-apps', true],
  ['shared_aweber', 'marketing', false],
  ['shared_azuread', 'identity', true],
  ['shared_azureadip', 'identity', true],
  ['shared_azureagentservice', 'ai', true],
  ['shared_azureaifoundryinference', 'ai', true],
  ['shared_azureaisearch', 'ai', true],
  ['shared_azureaisearchfoundryiq', 'ai', true],
  ['shared_azureappservice', 'azure', true],
  ['shared_azureautomation', 'azure', true],
  ['shared_azureblob', 'azure', true],
  ['shared_azurecommunicationservicessms', 'azure', true],
  ['shared_azuredatafactory', 'azure', true],
  ['shared_azuredatalake', 'azure', true],
  ['shared_azuredigitaltwins', 'azure', true],
  ['shared_azureeventgrid', 'azure', true],
  ['shared_azureeventgridpublish', 'azure', true],
  ['shared_azurefile', 'azure', true],
  ['shared_azureiotcentral', 'azure', true],
  ['shared_azureloganalytics', 'azure', true],
  ['shared_azureloganalyticsdatacollector', 'azure', true],
  ['shared_azuremaps', 'azure', true],
  ['shared_azuremonitorlogs', 'azure', true],
  ['shared_azuremonitorlogsingestion', 'azure', true],
  ['shared_azuremysql', 'azure', true],
  ['shared_azureopenai', 'ai', true],
  ['shared_azurequeues', 'azure', true],
  ['shared_azurespeechpronuncia', 'ai', true],
  ['shared_azuretables', 'azure', true],
  ['shared_azuretexttospeech', 'ai', true],
  ['shared_azurevm', 'azure', true],
  ['shared_basecamp', 'productivity', false],
  ['shared_basecamp2', 'productivity', false],
  ['shared_benchmarkemail', 'marketing', false],
  ['shared_bigcommerce', 'commerce', false],
  ['shared_bingmaps', 'data', true],
  ['shared_bingsearch', 'data', true],
  ['shared_bitbucket', 'devops', false],
  ['shared_bitly', 'marketing', false],
  ['shared_biztalk', 'integration', true],
  ['shared_blockchaincorda', 'blockchain', false],
  ['shared_blockchainethereum', 'blockchain', false],
  ['shared_blogger', 'content', false],
  ['shared_box', 'content', false],
  ['shared_bttn', 'iot', false],
  ['shared_buffer', 'marketing', false],
  ['shared_businessassist', 'business-apps', true],
  ['shared_calendly', 'productivity', false],
  ['shared_campfire', 'communication', false],
  ['shared_capsulecrm', 'crm', false],
  ['shared_casper365', 'education', false],
  ['shared_cgtrader', 'other', false],
  ['shared_chatter', 'crm', false],
  ['shared_cimcp', 'ai', true],
  ['shared_cloudappsecurity', 'security', true],
  ['shared_cognitiveservicescomputervision', 'ai', true],
  ['shared_cognitiveservicescontentmoderator', 'ai', true],
  ['shared_cognitiveservicescustomvision', 'ai', true],
  ['shared_cognitiveservicesqnamaker', 'ai', true],
  ['shared_cognitiveservicesspe', 'ai', true],
  ['shared_cognitiveservicestextanalytics', 'ai', true],
  ['shared_commercemerchandising', 'business-apps', true],
  // shared_commondataservice deliberately excluded — duplicate of shared_commondataserviceforapps
  ['shared_commondataserviceforapps', 'data', true],
  ['shared_confluence', 'productivity', false],
  ['shared_contentunderstanding', 'ai', true],
  ['shared_contosohub', 'other', true],
  ['shared_conversionservice', 'content', true],
  ['shared_copilotflow', 'ai', true],
  ['shared_copilotforfinance', 'ai', true],
  ['shared_copilotforsales', 'ai', true],
  ['shared_copilotforservice', 'ai', true],
  ['shared_customerinsights', 'business-apps', true],
  ['shared_d365contactcenteradminmcpserver', 'ai', true],
  ['shared_d365contactcentermcpserver', 'ai', true],
  ['shared_d365salesmcpserver', 'ai', true],
  ['shared_dancharttest', 'other', true],
  ['shared_dataactivatorpreview', 'data', true],
  ['shared_dataflows', 'data', true],
  ['shared_db2', 'data', false],
  ['shared_defendersoc', 'security', true],
  ['shared_disqus', 'content', false],
  ['shared_documentdb', 'azure', true],
  ['shared_dynamics365ratingsre', 'business-apps', true],
  ['shared_dynamicsax', 'business-apps', true],
  ['shared_dynamicsfraudprotect', 'business-apps', true],
  ['shared_dynamicsnavision', 'business-apps', true],
  ['shared_dynamicssmbonprem', 'business-apps', true],
  ['shared_dynamicssmbsaas', 'business-apps', true],
  ['shared_dynamicstranslations', 'business-apps', true],
  ['shared_easyredmine', 'productivity', false],
  ['shared_eduframe', 'education', false],
  ['shared_eventbrite', 'productivity', false],
  ['shared_eventhubs', 'azure', true],
  ['shared_excel', 'productivity', true],
  ['shared_excelonline', 'productivity', true],
  ['shared_excelonlinebusiness', 'productivity', true],
  ['shared_fabriciqmcpserver', 'ai', true],
  ['shared_faceapi', 'ai', true],
  ['shared_fhirbase', 'health', true],
  ['shared_fhirclinical', 'health', true],
  ['shared_filesystem', 'content', true],
  ['shared_flic', 'iot', false],
  ['shared_flowmanagement', 'productivity', true],
  ['shared_flowpush', 'productivity', true],
  ['shared_formrecognizer', 'ai', true],
  ['shared_freshbooks', 'finance', false],
  ['shared_freshdesk', 'support', false],
  ['shared_freshservice', 'support', false],
  ['shared_ftp', 'content', true],
  ['shared_github', 'devops', false],
  ['shared_googlecalendar', 'productivity', false],
  ['shared_googlecontacts', 'productivity', false],
  ['shared_googledrive', 'content', false],
  ['shared_googlesheet', 'productivity', false],
  ['shared_googletasks', 'productivity', false],
  ['shared_gototraining', 'productivity', false],
  ['shared_gotowebinar', 'productivity', false],
  ['shared_harvest', 'productivity', false],
  ['shared_hellosign', 'productivity', false],
  ['shared_hipchat', 'communication', false],
  ['shared_impala', 'data', false],
  ['shared_informix', 'data', false],
  ['shared_infusionsoft', 'marketing', false],
  ['shared_inoreader', 'content', false],
  ['shared_insightly', 'crm', false],
  ['shared_instapaper', 'content', false],
  ['shared_intentionaldatasources', 'data', true],
  ['shared_intercom', 'support', false],
  ['shared_iotcentral', 'azure', true],
  ['shared_jbhunt', 'other', false],
  ['shared_jira', 'productivity', false],
  ['shared_jupyrest', 'other', true],
  ['shared_kaizala', 'communication', true],
  ['shared_keyvault', 'azure', true],
  ['shared_kusto', 'azure', true],
  ['shared_leankit', 'productivity', false],
  ['shared_lifx', 'iot', false],
  ['shared_linkedin', 'social', false],
  ['shared_linkedinv2', 'social', false],
  ['shared_livechat', 'support', false],
  ['shared_logicflows', 'productivity', true],
  ['shared_luis', 'ai', true],
  ['shared_m365messagecenter', 'productivity', true],
  ['shared_m365updatesapp', 'productivity', true],
  ['shared_mailchimp', 'marketing', false],
  ['shared_mandrill', 'marketing', false],
  ['shared_medium', 'content', false],
  ['shared_microsoft365compliance', 'security', true],
  ['shared_microsoftbookings', 'productivity', true],
  ['shared_microsoftcopilotstudio', 'ai', true],
  ['shared_microsoftflowforadmins', 'productivity', true],
  ['shared_microsoftforms', 'productivity', true],
  ['shared_microsoftformspro', 'business-apps', true],
  ['shared_microsoftgraphsecurity', 'security', true],
  ['shared_microsoftlearndocsmcpserver', 'ai', true],
  ['shared_microsoftloop', 'productivity', true],
  ['shared_microsoftpartnercent', 'business-apps', true],
  ['shared_microsoftschooldatas', 'education', true],
  ['shared_microsoftsearch', 'productivity', true],
  ['shared_microsofttranslator', 'ai', true],
  ['shared_msnweather', 'data', true],
  ['shared_mysql', 'data', false],
  ['shared_narvar', 'commerce', false],
  ['shared_nexmo', 'communication', false],
  ['shared_office365', 'communication', true],
  ['shared_office365groups', 'communication', true],
  ['shared_office365groupsmail', 'communication', true],
  ['shared_office365users', 'communication', true],
  ['shared_office365video', 'content', true],
  ['shared_officeaiagent', 'ai', true],
  ['shared_onenote', 'productivity', true],
  ['shared_oracle', 'data', false],
  ['shared_outlook', 'communication', true],
  ['shared_outlooktasks', 'productivity', true],
  ['shared_pagerduty', 'support', false],
  ['shared_partnercenterevents', 'business-apps', true],
  ['shared_partnercenterref', 'business-apps', true],
  ['shared_personr', 'other', false],
  ['shared_pinterest', 'social', false],
  ['shared_pipedrive', 'crm', false],
  ['shared_pivotaltracker', 'productivity', false],
  ['shared_planner', 'productivity', true],
  ['shared_postgresql', 'data', false],
  ['shared_powerappsforadmins', 'productivity', true],
  ['shared_powerappsforappmakers', 'productivity', true],
  ['shared_powerappsnotification', 'productivity', true],
  ['shared_powerappsnotificationv2', 'productivity', true],
  ['shared_powerbi', 'data', true],
  ['shared_powerplatformadminv2', 'productivity', true],
  ['shared_powerplatformforadmins', 'productivity', true],
  ['shared_powervirtualagents', 'ai', true],
  ['shared_processmining', 'data', true],
  ['shared_projectonline', 'productivity', true],
  ['shared_projectroadmap', 'productivity', true],
  ['shared_redmine', 'productivity', false],
  ['shared_riskiqintelligence', 'security', true],
  ['shared_rss', 'content', true],
  ['shared_saperp', 'business-apps', false],
  ['shared_sapodata', 'business-apps', false],
  ['shared_securitycopilot', 'security', true],
  ['shared_sendgrid', 'marketing', false],
  ['shared_sentinelmcp', 'security', true],
  ['shared_service-now', 'support', false],
  ['shared_servicebus', 'azure', true],
  // shared_servicebus-1 deliberately excluded — duplicate of shared_servicebus
  ['shared_sftp', 'content', true],
  ['shared_sftpwithssh', 'content', true],
  ['shared_sharepointembedded', 'content', true],
  ['shared_shifts', 'communication', true],
  ['shared_shop', 'commerce', false],
  ['shared_skypeforbiz', 'communication', true],
  ['shared_slack', 'communication', false],
  ['shared_smartsheet', 'productivity', false],
  ['shared_smtp', 'communication', true],
  ['shared_sparkpost', 'marketing', false],
  ['shared_sqldw', 'azure', true],
  ['shared_storeoperationsmcpserver', 'ai', true],
  ['shared_stripe', 'finance', false],
  ['shared_surveymonkey', 'productivity', false],
  ['shared_teams', 'communication', true],
  ['shared_teamsvirtualevents', 'communication', true],
  ['shared_teamwork', 'productivity', false],
  ['shared_teradata', 'data', false],
  ['shared_tilkee', 'productivity', false],
  ['shared_todo', 'productivity', true],
  ['shared_todoconsumer', 'productivity', true],
  ['shared_todoist', 'productivity', false],
  ['shared_toodledo', 'productivity', false],
  ['shared_translatorv2', 'ai', true],
  ['shared_trello', 'productivity', false],
  ['shared_twilio', 'communication', false],
  ['shared_twitter', 'social', false],
  ['shared_typeform', 'productivity', false],
  ['shared_uberfreight', 'logistics', false],
  ['shared_uiflow', 'productivity', true],
  ['shared_uservoice', 'support', false],
  ['shared_videoindexer-v2', 'ai', true],
  ['shared_vimeo', 'content', false],
  ['shared_virustotal', 'security', false],
  ['shared_visualstudioteamservices', 'devops', true],
  ['shared_wdatp', 'security', true],
  ['shared_webcontents', 'integration', true],
  ['shared_webcontentsv2', 'integration', true],
  ['shared_windows365', 'productivity', true],
  ['shared_wordonlinebusiness', 'productivity', true],
  ['shared_wordpress', 'content', false],
  ['shared_workdayhcm', 'business-apps', false],
  ['shared_workdaysoap', 'business-apps', false],
  ['shared_workiqmcp', 'ai', true],
  ['shared_workiqonedrive', 'ai', true],
  ['shared_workiqsharepoint', 'ai', true],
  ['shared_yammer', 'communication', true],
  ['shared_zendesk', 'support', false],
];

async function main() {
  await connectDb(config.CSGE_DB);

  let ok = 0;
  const notInstalled: string[] = [];
  const errored: string[] = [];

  for (const [connectorId, category, isMicrosoftOwnService] of CONNECTORS) {
    process.stdout.write(`${connectorId}... `);
    try {
      const index = await captureOpIndex(connectorId, CTX);
      if (!index) {
        console.log('not available in this environment');
        notInstalled.push(connectorId);
        continue;
      }
      const { connector, operations } = toRegistryRecords(
        connectorId,
        isMicrosoftOwnService ? 'Microsoft' : 'Microsoft (third-party wrapper)',
        isMicrosoftOwnService,
        category,
        index,
      );
      await putConnector(connector);
      await putConnectorOperations(connectorId, operations);
      console.log(`OK — ${operations.length} operations`);
      ok++;
    } catch (e) {
      console.log(`ERROR: ${(e as Error).message}`);
      errored.push(connectorId);
    }
  }

  console.log(`\n=== Done ===`);
  console.log(`Captured and written: ${ok}/${CONNECTORS.length}`);
  console.log(`Not installed in this environment: ${notInstalled.length}`);
  console.log(`Errored: ${errored.length}`);
  if (errored.length) console.log(`Errored ids: ${errored.join(', ')}`);

  await closeDb();
}

main().catch((e) => {
  console.error('FAILED:', e);
  process.exit(1);
});
